language: python

python:
  - "3.6"
  - "3.7"

script:
  - pip install -r requirements.txt
  - pip install .
  - py.test

after_success:
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) && ( "$TRAVIS_PULL_REQUEST" == "false" ) ]]; then
    make publish;
    fi
